bookers_app/config/routes.rb
Rails.application.routes.draw do
  get root :to=>'books#top'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  get 'books/:id' => 'books#show', as: 'book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers_app/app/models/book.rb
class Book < ApplicationRecord
 validates :title, presence: true
 validates :body, presence: true
end

bookers_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
        flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index


    end
  end

  def index
   @books = Book.all
   @book = Book.new
  end

  def show
     @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

bookers_app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers_app/app/helpers/books_helper.rb
module BooksHelper
end

bookers_app/app/helpers/homes_helper.rb
module HomesHelper
end

bookers_app/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local: true do |f| %>
  <div class="filed">
  <label for="book_title">Title</label>
<br>
  <%= f.text_field :title %>
</div>
<div class="filed">
  <label for="book_title">Body</label>
  <br>
  <%= f.text_area :body %>
 </div>
   <%= f.submit 'Update Book' %>
<span>
    <%= link_to "Show", book_path(@book.id) %>
    |
    <%= link_to "Back", books_path %>
  </span>
<% end %>

bookers_app/app/views/books/index.html.erb
 <body>
<p id="notice"></p>
 <h1>Books</h1>
  <table>
      <thead>
          <tr>
           <th>Title</th>
           <th>Body</th>
           <th colspan = "3"></th>
          </tr>
      </thead>
    <today>
     <% @books.each do |book| %>
     <tr>
       <td><span><%= book.title %></span></td>
       <td><span><%= book.body %></span></td>
       <td><span><%= link_to "Show", book_path(book) %></span></td>
       <td><span><%= link_to "Edit", edit_book_path(book) %></span></td>
       <td><span><%= link_to "Destroy", destroy_book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></span></td>
      </tr>
     <% end %>
    </today>
 </table>

<h2>New book</h2>
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post, local:true do |f| %>
<div class="filed">
  <label for="book_title">Title</label>
<br>
  <%= f.text_field :title %>
</div>
<div class="filed">
  <label for="book_title">Body</label>
  <br>
  <%= f.text_area :body %>
 </div>
  <%= f.submit 'Create Book' %>
<% end %>
</body>

bookers_app/app/views/books/show.html.erb
<%= flash[:notice] %>
<p><strong>Title:</strong>
<%= @book.title %></p>

<p><strong>Body:</strong>
<%= @book.body %></p>
<span>
    <%= link_to "Edit", edit_book_path(@book.id) %>
    |
    <%= link_to "Back", "/books" %>
  </span>

bookers_app/app/views/books/top.html.erb
<%= form_with model: @book, local: true do |f| %>
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<span>
    <%= link_to "start", "/books" %>
  </span>
<% end %>

bookers_app/app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

bookers_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>